<?php

use Phinx\Seed\AbstractSeed;

class ClientesSeeder extends AbstractSeed {

    protected $nombres = [
        'AARON',
        'ABEL',
        'ABELARDO',
        'ABIGAÍL',
        'ABRAHAM',
        'ABRIL',
        'ADA',
        'ADALBERTO',
        'ADÁN',
        'ADELA',
        'ADELAIDA',
        'ADELINA',
        'ADELMO',
        'ADOLFO',
        'ADRIÁN',
        'ADRIANO',
        'ÁGATA',
        'ÁGUEDA',
        'AGUSTÍN',
        'AÍDA',
        'AINARA',
        'ALAN',
        'ALBANO',
        'ALBERTO',
        'ALCIRA',
        'ALDO',
        'ALEJANDRO',
        'ALEJANDRA',
        'ALEJO',
        'ALFONSO',
        'ALFREDO',
        'ALICIA',
        'ALINA',
        'ALMUDENA',
        'ALONSO',
        'ÁLVARO',
        'AMADEO',
        'AMALIA',
        'AMANCIO',
        'AMANDA',
        'AMARANTO',
        'AMAYA',
        'AMOS',
        'AMBROSIO',
        'AMELIA',
        'AMIRA',
        'AMPARO',
        'ANA',
        'ANACLETO',
        'ANASTASIA',
        'ANDER',
        'ANDRÉS',
        'ÁNGEL',
        'ANGÉLICA',
        'ÁNGELES',
        'ANÍBAL',
        'ANICETO',
        'ANGUSTIAS',
        'ANSELMO',
        'ANTONIO',
        'ANTONIA',
        'ANTONIETA',
        'APOLO',
        'AQUILES',
        'AQUILINO',
        'ARACELI',
        'ARCHIBALDO',
        'ARIADNA',
        'ARIEL',
        'ARÍSTIDES',
        'ARMANDO',
        'ARNOLDO',
        'ARTURO',
        'ASUNCIÓN',
        'ATANASIO',
        'AUGUSTO',
        'AURELIO',
        'AURELIA',
        'AURORA',
        'AUXILIADORA',
        'AXEL',
        'AZUZENA',
        'EDGARDO',
        'EDITH',
        'EDMUNDO',
        'EDUARDO',
        'EFRAÍN',
        'EFRÉN',
        'ELENA',
        'ELEONOR',
        'ELÍAS',
        'ELISA',
        'ELISABETH',
        'ELOISA',
        'ELOY',
        'ELSA',
        'ELVIRA',
        'EMILIA',
        'EMILIO',
        'EMA',
        'EMANUEL',
        'EMILIO',
        'ENCARNACIÓN',
        'ENGRACIA',
        'ENRIQUE',
        'ERASMO',
        'ERICO',
        'ERIC',
        'ERICA',
        'ERNESTO',
        'ESMERALDA',
        'ESPERANZA',
        'ESTEBAN',
        'ESTEFANÍA',
        'ESTELA',
        'ESTER',
        'ETEL',
        'EUCLIDES',
        'EUDOSIA',
        'EUDOXIO',
        'EUFEMIO',
        'EUFEMIA',
        'EUFRASIO',
        'EUFRASIA',
        'EUGENIO',
        'EUGENIA',
        'EULALIO',
        'EULALIA',
        'EUSEBIO',
        'EUSTAQUIO',
        'EVA',
        'EVANGELINA',
        'EVARISTO',
        'EZEQUIEL',
        'RAFAEL',
        'RAIMUNDO',
        'RAMIRO',
        'RAMONA',
        'RAMÓN',
        'RAQUEL',
        'RAÚL',
        'REBECA',
        'REINA',
        'REINALDO',
        'REGINA',
        'REMEDIOS',
        'RENATO',
        'RENÉ',
        'RICARDO',
        'RITA',
        'ROBERTO',
        'ROCÍO',
        'RODOLFO',
        'RODRIGO',
        'ROGELIO',
        'ROLANDO',
        'ROMÁN',
        'ROMEO',
        'ROMILDA',
        'ROMILDO',
        'RONALDO',
        'ROQUE',
        'ROSA',
        'ROSALÍA',
        'ROSAMUNDA',
        'ROSANA',
        'ROSARIO',
        'ROSENDO',
        'ROXANA',
        'RUBÉN',
        'RUFINO',
        'RUPERTO',
        'RUTH',
    ];
    protected $apellidos = [
        'Abad',
        'Adadia',
        'Abascal',
        'Abella',
        'Abellán',
        'Abril',
        'Acedo',
        'Acevedo',
        'Acero',
        'Acosta',
        'Acuña',
        'Adán',
        'Aguado',
        'Agudo',
        'Águila',
        'Aguilar',
        'Aguilera',
        'Aguiló',
        'Aguirre',
        'Agullo',
        'Agustí',
        'Agustín',
        'Álamo',
        'Alarcón',
        'Alba',
        'Alberdi',
        'Albero',
        'Alberola',
        'Alberto',
        'Alcalá',
        'Alcalde',
        'Alcántara',
        'Alcaraz',
        'Alcázar',
        'Alcolea',
        'Alegre',
        'Alegria',
        'Alemán',
        'Alemany',
        'Alfaro',
        'Alfonso',
        'Aliaga',
        'Almagro',
        'Almansa',
        'Almazán',
        'Almeida',
        'Alonso',
        'Alsina',
        'Alvarado',
        'Álvarez',
        'Álvaro',
        'Aller',
        'Amador',
        'Amat',
        'Amaya',
        'Amigó',
        'Amo',
        'Amor',
        'Amores',
        'Amorós',
        'Anaya',
        'Andrade',
        'Andrés',
        'Andreu',
        'Ángel',
        'Anglada',
        'Angulo',
        'Anguita',
        'Antón',
        'Antúnez',
        'Aparicio',
        'Aragón',
        'Aragonés',
        'Aramburu',
        'Arana',
        'Aranda',
        'Araujo',
        'Arce',
        'Arco',
        'Arcos',
        'Arellano',
        'Arenas',
        'Arévalo',
        'Arias',
        'Ariño',
        'Ariza',
        'Arjona',
        'Armas',
        'Armengol',
        'Arnaiz',
        'Arnal',
        'Arnau',
        'Aroca',
        'Arranz',
        'Arregui',
        'Arribas',
        'Arrieta',
        'Arroyo',
        'Arteaga',
        'Artigas',
        'Asenjo',
        'Asensio',
        'Atienza',
        'Ávila',
        'Avilés',
        'Ayala',
        'Ayllón',
        'Ayuso',
        'Azcona',
        'Aznar',
        'Azorin',
        'Badía',
        'Baena',
        'Báez',
        'Baeza',
        'Balaguer',
        'Ballester',
        'Ballesteros',
        'Baños',
        'Baquero',
        'Barba',
        'Barberá',
        'Barbero',
        'Barceló',
        'Bárcena',
        'Barco',
        'Baró',
        'Barón',
        'Barragán',
        'Barral',
        'Barranco',
        'Barreda',
        'Barrena',
        'Barrera',
        'Barriga',
        'Barrio',
        'Barrios',
        'Barros',
        'Barroso',
        'Bartolomé',
        'Bas',
        'Bastida',
        'Batalla',
        'Batlle',
        'Bautista',
        'Bauzà',
        'Bayo',
        'Bayón',
        'Bayona',
        'Becerra',
        'Bejarano',
        'Belda',
        'Belmonte',
        'Beltrán',
        'Bellido',
        'Bello',
        'Benavent',
        'Benavente',
        'Benavides',
        'Benet',
        'Benítez',
        'Benito',
        'Berenguer',
        'Bermejo',
        'Bermúdez',
        'Bernad',
        'Bernal',
        'Bernat',
        'Berrocal',
        'Bertrán',
        'Bilbao',
        'Blanca',
        'Blanco',
        'Blanch',
        'Blanes',
        'Blasco',
        'Blázquez',
        'Boada',
        'Boix',
        'Bolaños',
        'Bonet',
        'Bonilla',
        'Borja',
        'Borrás',
        'Borrego',
        'Borrell',
        'Bosch',
        'Botella',
        'Bou',
        'Bravo',
        'Briones',
        'Bru',
        'Buendía',
        'Bueno',
        'Burgos',
        'Busquets',
        'Bustamante',
        'Bustos',
        'Caballero',
        'Cabanillas',
        'Cabañas',
        'Cabello',
        'Cabeza',
        'Cabezas',
        'Cabo',
        'Cabrera',
        'Cabrero',
        'Cáceres',
        'Cadenas',
        'Cal',
        'Calatayud',
        'Calderón',
        'Calvet',
        'Calvo',
        'Calleja',
        'Calzada',
        'Camacho',
        'Cámara',
        'Camino',
        'Campillo',
        'Campo',
        'Campos',
        'Campoy',
        'Camps',
        'Canales',
        'Canals',
        'Canet',
        'Cano',
        'Cánovas',
        'Cantero',
        'Cantón',
        'Cañas',
        'Cañellas',
        'Cañete',
        'Cañizares',
        'Caparrós',
        'Capdevila',
        'Carballo',
        'Carbajo',
        'Carbó',
        'Carbonell',
        'Cárdenas',
        'Cardona',
        'Carlos',
        'Carmona',
        'Carnero',
        'Caro',
        'Carpio',
        'Carranza',
        'Carrasco',
        'Carreño',
        'Carrera',
        'Carreras',
        'Carretero',
        'Carrillo',
        'Carrión',
        'Carro',
        'Carvajal',
        'Casado',
        'Casal',
        'Casals',
        'Casanova',
        'Casanovas',
        'Casares',
        'Casas',
        'Cases',
        'Castañeda',
        'Castejón',
        'Castell',
        'Castellanos',
        'Castelló',
        'Castells',
        'Castilla',
        'Castillo',
        'Castrillo',
        'Castro',
        'Catalá',
        'Catalán',
        'Cazorla',
        'Cepeda',
        'Cerdá',
        'Cerdán',
        'Cerezo',
        'Cerro',
        'Cervantes',
        'Cervera',
        'Céspedes',
        'Cid',
        'Cifuentes',
        'Cisneros',
        'Clavero',
        'Clemente',
        'Cobo',
        'Cobos',
        'Coca',
        'Codina',
        'Coello',
        'Colom',
        'Coloma',
        'Colomer',
        'Coll',
        'Collado',
        'Comas',
        'Company',
        'Conde',
        'Conesa',
        'Contreras',
        'Corbacho',
        'Cordero',
        'Córdoba',
        'Cornejo',
        'Corominas',
        'Coronado',
        'Corral',
        'Correa',
        'Cortés',
        'Cortina',
        'Costa',
        'Cózar',
        'Criado',
        'Crespi',
        'Crespo',
        'Cruz',
        'Cuadrado',
        'Cuéllar',
        'Cuenca',
        'Cuervo',
        'Cuesta',
        'Cueto',
        'Cuevas',
        'Chacón',
        'Chamorro',
        'Chaparro',
        'Chaves',
        'Checa',
        'Chico',
        'Dalmau',
        'Dávila',
        'Daza',
        'Delgado',
        'Díaz',
        'Diego',
        'Diéguez',
        'Díez',
        'Doménech',
        'Domingo',
        'Domínguez',
        'Donaire',
        'Donoso',
        'Duarte',
        'Dueñas',
        'Duque',
        'Durán',
        'Echevarría',
        'Echeverría',
        'Egea',
        'Elías',
        'Elorza',
        'Enríquez',
        'Escalona',
        'Escamilla',
        'Escobar',
        'Escolano',
        'Escribano',
        'Escrivá',
        'Escudero',
        'Espada',
        'España',
        'Español',
        'Esparza',
        'Espejo',
        'Espinosa',
        'Esteban',
        'Esteve',
        'Estévez',
        'Estrada',
        'Expósito',
        'Fabra',
        'Fábregas',
        'Fabregat',
        'Fajardo',
        'Falcó',
        'Falcón',
        'Farré',
        'Feijoo',
        'Feliu',
        'Fernández',
        'Ferrán',
        'Ferrández',
        'Ferrándiz',
        'Ferrando',
        'Ferrer',
        'Ferrera',
        'Ferrero',
        'Ferreras',
        'Figueras',
        'Figueroa',
        'Figuerola',
        'Fiol',
        'Flor',
        'Flores',
        'Folch',
        'Fonseca',
        'Font',
        'Fortuny',
        'Franch',
        'Francisco',
        'Franco',
        'Franch',
        'Frías',
        'Frutos',
        'Fuente',
        'Fuentes',
        'Fuertes',
        'Fuster',
        'Gabaldón',
        'Galán',
        'Galiano',
        'Galindo',
        'Galván',
        'Gálvez',
        'Gallardo',
        'Gallart',
        'Gallego',
        'Gallo',
        'Gámez',
        'Gárate',
        'Garay',
        'Garcés',
        'García',
        'Gargallo',
        'Garmendia',
        'Garrido',
        'Garriga',
        'Garzón',
        'Gascón',
        'Gaya',
        'Gelabert',
        'Gibert',
        'Gil',
        'Gilabert',
        'Giménez',
        'Gimeno',
        'Giner',
        'Giralt',
        'Girón',
        'Girona',
        'Gisbert',
        'Godoy',
        'Goicoechea',
        'Gómez',
        'Gomila',
        'Gomis',
        'González',
        'Gonzalo',
        'Goñi',
        'Gordillo',
        'Gracia',
        'Granados',
        'Grande',
        'Gras',
        'Grau',
        'Gual',
        'Guardia',
        'Guardiola',
        'Guerra',
        'Guerrero',
        'Guijarro',
        'Guillén',
        'Guitart',
        'Gutiérrez',
        'Guzmán',
        'Haro',
        'Heras',
        'Heredia',
        'Hernández',
        'Hernando',
        'Herranz',
        'Herrera',
        'Herrero',
        'Hervás',
        'Hervia',
        'Hidalgo',
        'Hierro',
        'Higueras',
        'Hoyos',
        'Hoz',
        'Huerta',
        'Huertas',
        'Huguet',
        'Hurtado',
        'Ibáñez',
        'Ibarra',
        'Iborra',
        'Iglesia',
        'Iglesias',
        'Infante',
        'Iniesta',
        'Íñigo',
        'Iñiguez',
        'Iriarte',
        'Isern',
        'Izaguirre',
        'Izquierdo',
        'Jaén',
        'Jara',
        'Jaume',
        'Jáuregui',
        'Jerez',
        'Jiménez',
        'Jódar',
        'Jordá',
        'Jordán',
        'Jove',
        'Jover',
        'Juan',
        'Juárez',
        'Juliá',
        'Julián',
        'Jurado',
        'Lago',
        'Laguna',
        'Lamas',
        'Landa',
        'Lara',
        'Larrañaga',
        'Larrea',
        'Lasa',
        'Lastra',
        'Leal',
        'Ledesma',
        'Leiva',
        'León',
        'Lerma',
        'Lillo',
        'Linares',
        'Lobato',
        'Lobo',
        'López',
        'Lorenzo',
        'Losa',
        'Losada',
        'Lozano',
        'Lucas',
        'Lucena',
        'Luís',
        'Luján',
        'Lumbreras',
        'Luna',
        'Luque',
        'Luz',
        'Llabrés',
        'Lladó',
        'Llamas',
        'Llano',
        'Llanos',
        'Lledó',
        'Llobet',
        'Llopis',
        'Llorens',
        'Llorente',
        'Lloret',
        'Lluch',
        'Macías',
        'Machado',
        'Madrid',
        'Madrigal',
        'Maestre',
        'Maldonado',
        'Malo',
        'Mancebo',
        'Manjón',
        'Manrique',
        'Manso',
        'Manuel',
        'Manzanares',
        'Manzano',
        'Marco',
        'Marcos',
        'Marí',
        'Marín',
        'Mariño',
        'Mariscal',
        'Mármol',
        'Marqués',
        'Márquez',
        'Martí',
        'Martín',
        'Martínez',
        'Martorell',
        'Mas',
        'Mascaró',
        'Mata',
        'Matas',
        'Mate',
        'Mateo',
        'Mateos',
        'Mateu',
        'Mayo',
        'Mayol',
        'Mayoral',
        'Maza',
        'Medina',
        'Meléndez',
        'Melero',
        'Mena',
        'Méndez',
        'Mendizábal',
        'Mendoza',
        'Menéndez',
        'Mercader',
        'Merino',
        'Mesa',
        'Miguel',
        'Milla',
        'Millán',
        'Mínguez',
        'Mir',
        'Miralles',
        'Miranda',
        'Miró',
        'Moles',
        'Molina',
        'Moliner',
        'Molins',
        'Moll',
        'Monreal',
        'Montalbán',
        'Montaña',
        'Montenegro',
        'Montero',
        'Montes',
        'Montesinos',
        'Montoya',
        'Montserrat',
        'Mora',
        'Moraleda',
        'Morales',
        'Morán',
        'Morante',
        'Morata',
        'Morcillo',
        'Morell',
        'Moreno',
        'Morera',
        'Morillo',
        'Mosquera',
        'Moya',
        'Múgica',
        'Mulet',
        'Múñiz',
        'Muñoz',
        'Mur',
        'Murcia',
        'Murillo',
        'Muro',
        'Nadal',
        'Naranjo',
        'Narváez',
        'Navarrete',
        'Navarro',
        'Navas',
        'Nebot',
        'Neira',
        'Nevado',
        'Nicolau',
        'Nicolás',
        'Nieto',
        'Niño',
        'Nogueira',
        'Noguera',
        'Nogués',
        'Noriega',
        'Novoa',
        'Núñez',
        'Ocaña',
        'Ochoa',
        'Ojeda',
        'Oliva',
        'Olivares',
        'Olivé',
        'Oliver',
        'Olivera',
        'Oliveras',
        'Olmedo',
        'Olmo',
        'Oller',
        'Ordóñez',
        'Orozco',
        'Ortega',
        'Ortiz',
        'Ortuño',
        'Osorio',
        'Osuna',
        'Otero',
        'Pablo',
        'Pacheco',
        'Padilla',
        'Páez',
        'Pagès',
        'Palacio',
        'Palacios',
        'Palau',
        'Palma',
        'Palmer',
        'Palomar',
        'Palomares',
        'Palomino',
        'Palomo',
        'Pallarès',
        'Paniagua',
        'Pardo',
        'Paredes',
        'Pareja',
        'Parejo',
        'Parra',
        'Pascual',
        'Pastor',
        'Patiño',
        'Pavón',
        'Paz',
        'Pazos',
        'Pedraza',
        'Pedrero',
        'Pedro',
        'Pedrosa',
        'Peinado',
        'Peiró',
        'Peláez',
        'Pelayo',
        'Pellicer',
        'Peña',
        'Peñalver',
        'Peñas',
        'Pera',
        'Peral',
        'Perales',
        'Peralta',
        'Perea',
        'Pereira',
        'Perelló',
        'Perera',
        'Pérez',
        'Pi',
        'Pina',
        'Pineda',
        'Pinedo',
        'Pinilla',
        'Pino',
        'Pinto',
        'Pintor',
        'Piña',
        'Piñeiro',
        'Piñol',
        'Piquer',
        'Pizarro',
        'Pla',
        'Plana',
        'Planas',
        'Plaza',
        'Pol',
        'Polo',
        'Pomares',
        'Pombo',
        'Ponce',
        'Pons',
        'Pont',
        'Porcel',
        'Porras',
        'Porta',
        'Portero',
        'Portillo',
        'Posada',
        'Pou',
        'Poza',
        'Pozo',
        'Pozuelo',
        'Prada',
        'Prado',
        'Prat',
        'Prats',
        'Priego',
        'Prieto',
        'Puente',
        'Puerta',
        'Puga',
        'Puig',
        'Pujadas',
        'Pujol',
        'Pulido',
        'Quero',
        'Querol',
        'Quesada',
        'Quevedo',
        'Quintana',
        'Quintanilla',
        'Quintero',
        'Quiroga',
        'Quirós',
        'Ramírez',
        'Ramis',
        'Ramón',
        'Ramos',
        'Raya',
        'Real',
        'Rebollo',
        'Recio',
        'Redondo',
        'Reguera',
        'Reig',
        'Reina',
        'Requena',
        'Revilla',
        'Rey',
        'Reyes',
        'Riba',
        'Ribas',
        'Ribera',
        'Ribes',
        'Ricart',
        'Rico',
        'Riera',
        'Rincón',
        'Río',
        'Ríos',
        'Ripoll',
        'Riquelme',
        'Rius',
        'Rivero',
        'Robledo',
        'Robles',
        'Roca',
        'Rocamora',
        'Rocha',
        'Roda',
        'Ródenas',
        'Rodrigo',
        'Rodríguez',
        'Roig',
        'Rojas',
        'Roldán',
        'Roma',
        'Román',
        'Romero',
        'Romeu',
        'Ropero',
        'Ros',
        'Rosa',
        'Rosado',
        'Rosales',
        'Rosell',
        'Roselló',
        'Rosselló',
        'Roura',
        'Rovira',
        'Royo',
        'Rozas',
        'Ruano',
        'Rubio',
        'Rueda',
        'Ruiz',
        'Saavedra',
        'Sabater',
        'Sacristán',
        'Sáenz',
        'Sáez',
        'Sainz',
        'Sala',
        'Salamanca',
        'Salas',
        'Salazar',
        'Salcedo',
        'Saldaña',
        'Sales',
        'Salgado',
        'Salinas',
        'Salmerón',
        'Salom',
        'Salvà',
        'Salvador',
        'Samper',
        'Sanabria',
        'Sánchez',
        'Sancho',
        'Sandoval',
        'Sanjuan',
        'Sanmartín',
        'Sanmiguel',
        'Sans',
        'Santamaría',
        'Santos',
        'Sanz',
        'Sarabia',
        'Sarmiento',
        'Sastre',
        'Saura',
        'Sebastián',
        'Seco',
        'Sedano',
        'Segarra',
        'Segovia',
        'Seguí',
        'Segura',
        'Serna',
        'Serra',
        'Serrano',
        'Sevilla',
        'Sevillano',
        'Sierra',
        'Silva',
        'Simó',
        'Sobrino',
        'Sola',
        'Solana',
        'Solano',
        'Solé',
        'Soler',
        'Solera',
        'Solís',
        'Solsona',
        'Somoza',
        'Soria',
        'Soriano',
        'Sosa',
        'Sotelo',
        'Soto',
        'Suárez',
        'Sureda',
        'Taboada',
        'Talavera',
        'Tamarit',
        'Tamayo',
        'Tapia',
        'Tejada',
        'Tejedor',
        'Tejera',
        'Tejero',
        'Téllez',
        'Tello',
        'Tena',
        'Tenorio',
        'Terrón',
        'Teruel',
        'Tirado',
        'Toledo',
        'Tolosa',
        'Tomás',
        'Tomé',
        'Tormo',
        'Toro',
        'Torralba',
        'Torre',
        'Torrecilla',
        'Torrens',
        'Torrent',
        'Torrents',
        'Torres',
        'Torrijos',
        'Tovar',
        'Trillo',
        'Trujillo',
        'Tudela',
        'Tur',
        'Ugarte',
        'Ureña',
        'Uría',
        'Uriarte',
        'Uribe',
        'Urrutia',
        'Valbuena',
        'Valcárcel',
        'Valderrama',
        'Valdés',
        'Valencia',
        'Valenciano',
        'Valentín',
        'Valenzuela',
        'Valera',
        'Valero',
        'Valverde',
        'Vall',
        'Valle',
        'Vallejo',
        'Vallés',
        'Valls',
        'Vaquero',
        'Vara',
        'Varela',
        'Vargas',
        'Vázquez',
        'Vega',
        'Velasco',
        'Velázquez',
        'Vélez',
        'Vendrell',
        'Vera',
        'Verdejo',
        'Verdú',
        'Verdugo',
        'Vergara',
        'Viana',
        'Vicente',
        'Vicens',
        'Vidal',
        'Vigil',
        'Vila',
        'Vilanova',
        'Vilalta',
        'Vilaplana',
        'Vilar',
        'Villa',
        'Villalba',
        'Villalobos',
        'Villalonga',
        'Villanueva',
        'Villar',
        'Villaverde',
        'Villegas',
        'Villena',
        'Viña',
        'Viñas',
        'Vives',
        'Vizcaíno',
        'Yáñez',
        'Yuste',
        'Zabala',
        'Zabaleta',
        'Zamora',
        'Zamorano',
        'Zapata',
        'Zaragoza',
        'Zorrilla',
        'Zurita',
    ];
    protected $calles = [
        '1ª Travesía de Barreiro',
        '2 Travesía Barrio de Ribadavia',
        '2ª Travesia de Guixar',
        '2ª Travesía do Padre Celso',
        '3ª Travesía do Padre Celso',
        'Alameda Suárez Llanos',
        'Alcalde Gregorio Espino',
        'Alcalde Lavadores',
        'Alexandre Boveda',
        'Area Portuaria de Bouzas',
        'As Avenidas',
        'Av Aeroporto',
        'Av Alcalde de Lavadores',
        'Av Alcalde Gregorio Espino',
        'Av Alcalde Portanet',
        'Av Arquitecto Palacios',
        'Av Atlántida',
        'Av Balaídos',
        'Av Beiramar',
        'Av Buenos Aires',
        'Av Camelias',
        'Av Castelao',
        'Av Castrelos',
        'Av Cesar Augusto',
        'Av Cesáreo Vázquez',
        'Av Citroën',
        'Av da Florida',
        'Av da Ponte',
        'Av de Antonio Palacios',
        'Av de Castelao',
        'Av de Castrelos',
        'Av de Emilio Martínez Garrido',
        'Av de Europa',
        'Av de Fragoso',
        'Av de Galicia',
        'Av de la Florida',
        'Av de la Gran Vía',
        'Av de la Marina Española',
        'Av de las Camelias',
        'Av de Ramón Nieto',
        'Av de Ricardo Mella',
        'Av de Santa Marina',
        'Av del Marqués Alcedo',
        'Av del Samil',
        'Av del Tranvía',
        'Av García Barbón',
        'Av Hispanidad',
        'Av Madrid',
        'Avenida Doña Fermina',
        'Avenida Guixar',
        'Baixada á Praia',
        'Baixada A Ría',
        'Baixada á Roteas',
        'Baixada a Rúa do Mestre Chané',
        'Baixada a Salgueira',
        'Baixada a San Roque',
        'Baixada Castelo',
        'Baixada Castreliños',
        'Calle de la Revolta',
        'Calle de la Rola',
        'Calle de la Senra',
        'Calle de la Urbanización Mirasol',
        'Calle de la Vía',
        'Calle de la Viña Grande',
        'Calle de la Volta',
        'Calle de la Xeme',
        'Calle de Lalín',
        'Calle de las Angustias',
        'Calle de las Ánimas',
        'Calle de las Avenidas',
        'Calle de las Carballas',
        'Calle de las Cortellas',
        'Calle de las Coutadas',
        'Calle de las Coutadas-Salgueira',
        'Calle de las Devesas',
        'Calle de las Fontans',
        'Calle de las Huertas',
        'Calle de las Illas Baleares',
        'Calle de las Illas Canarias',
        'Calle de las Lilas',
        'Calle de las Maceiriñas',
        'Calle de las Moreiras',
        'Calle de las Ribelas',
        'Calle de las Saiñas',
        'Calle de Lavadeiro',
        'Calle de León',
        'Calle de Leonardo Alonso',
        'Calle de Lepanto',
        'Calle de Lirio',
        'Calle de Llorente',
        'Calle de Logroño',
        'Calle de Lombeiro            ',
        'Calle de Manuel Costas Bastos',
        'Calle de Manuel de Castro',
        'Calle de Manuel Lago Lago',
        'Calle de Manuel Núñez',
        'Calle de Manuel Olivie',
        'Calle de Marcelina Panete',
        'Calle de María Auxiliadora',
        'Calle de María Berdiales',
        'Calle de Marín',
        'Calle de Marqués de Valterra',
        'Calle de Martín Alonso Pinzón',
        'Calle de Martín Códax',
        'Calle de Martín Echegaray',
        'Calle de Medoña',
        'Calle de Melide',
        'Calle de Méndez Núñez',
        'Calle de Menéndez Pelayo',
        'Calle de Mercedes Ruibal',
        'Calle de Merlo',
        'Calle de Mestre Mateo',
        'Calle de México',
        'Calle de Moaña',
        'Calle de Molais',
        'Calle de Mondariz',
        'Calle de Monforte de Lemos',
        'Calle de Montecelo',
        'Calle de Montecelo Alto',
        'Calle de Montecelo Baixo',
        'Calle de Montero Ríos',
        'Calle de Mos',
        'Calle de Navarra',
        'Calle de Nicaragua',
        'Calle de Nigrán',
        'Calle de Nogueira',
        'Calle de Numancia',
        'Calle de Núñez de Balboa',
        'Calle de Obdulia Simón',
        'Calle de Olimpia Valencia',
        'Calle de Oliveira',
        'Calle de Oporto',
        'Calle de Otero Pedrayo',
        'Calle de Ourense',
        'Calle de Pablo Iglesias',
        'Calle de Pablo Morillo',
        'Calle de Padre Ramón María Aller',
        'Calle de Palencia',
        'Calle de Panamá',
        'Calle de Parachan',
        'Calle de Parada',
        'Calle de Paradela',
        'Calle de Paraguay',
        'Calle de Pardal',
        'Calle de Pardavila',
    ];

    private function aleatorio($lista) {
        return $lista[rand(0, count($lista) - 1)];
    }

    
   
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        for ($j = 1; $j < 100; $j++) {
            $clientes = [];
            for ($i = 1; $i < 100; $i++) {
                $clientes[] = [
                    'Nombre' => $this->aleatorio($this->nombres) . ' ' . $this->aleatorio($this->apellidos) . ' ' . $this->aleatorio($this->apellidos),
                    'razonsocial' => $this->aleatorio($this->nombres) . ' ' . $this->aleatorio($this->apellidos) . ' ' . $this->aleatorio($this->apellidos),
                    'nif' => 'A' . rand(10000000, 99999999),
                    'direccion' => $this->aleatorio($this->calles),
                    'codpostal' => '3620' . rand(1, 9),
                    'telefono' => rand(600000000, 999999999),
                    'movil' => rand(600000000, 799999999),
                    'fax' => rand(800000000, 999999999),
                    'estado' => '2018-03-31 2',
                    'fecha_creado' => date('Y-m-d H:m:s'),
                ];
            }


            $cliente = $this->table('clientes');
            $cliente->insert($clientes)
                    ->save();
        }
    }

}
